# Generated by Django 4.2.17 on 2024-12-23 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_id', models.CharField(max_length=100, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('company', models.CharField(max_length=200)),
                ('location', models.JSONField()),
                ('description', models.TextField(blank=True, null=True)),
                ('salary', models.JSONField(blank=True, null=True)),
                ('employment_type', models.CharField(max_length=50, null=True)),
                ('location_type', models.CharField(max_length=50, null=True)),
                ('posted_at', models.DateTimeField(null=True)),
                ('updated_at', models.DateTimeField(null=True)),
                ('details_url', models.URLField(max_length=500, null=True)),
                ('company_url', models.URLField(max_length=500, null=True)),
                ('company_logo', models.URLField(max_length=500, null=True)),
                ('is_easy_apply', models.BooleanField(default=False)),
                ('willing_to_sponsor', models.BooleanField(default=False)),
                ('employer_type', models.CharField(max_length=100, null=True)),
                ('guid', models.CharField(max_length=100, null=True)),
            ],
            options={
                'db_table': 'jobs',
                'ordering': ['-posted_at'],
            },
        ),
    ]
